### PR TITLE
Run prometheus/update.sh

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
:ping_pong: @tianon

**Comment by tianon** [comment]
For some reason the Actions check here has stalled and I can't cancel or retry it -- would you mind rebasing and force pushing so we can try again? :pray:

(The change looks great to me, thanks! :+1:)

**Comment by J0WI** [comment]
@tianon done

**Comment by tianon** [comment]
Thank you! :+1:

**Pull request merged**
