### PR TITLE
Add explicit variants to buildkit (rc, dev, 0.13, for now)

### PR DESCRIPTION
**Pull request by tianon**
This is something I've been considering doing for a while (since the 0.13 series of RCs, actually), but was never quite happy with -- the advent of https://github.com/tianon/dockerfiles/pull/743 needing a new 0.13 build encouraged me to Do The Thing (specifically to include a "0.13" variant so we can do a rebuild of 0.13 with that backported patch so we can fix the current Kong build issue in DOI _without_ also introducing other potential issues by doing a full upgrade to 0.14 just yet).

FYI @yosifkit @whalelines @laurentgoderre - new `tianon/buildkit:0.13` incoming which _should_ fix the Kong build issues (thanks to #743, although I still think we need to continue exploring #742).

### CODE REVIEW

**Comment by tianon** [comment]
(had to exclude my "backport" patch on dev where it's already fixed :smile:)

**Comment by tianon** [comment]
My favorite way to review `gsl.sh` changes:

```diff
$ diff -u path-to/tianon-bashbrew/library/buildkit <(./gsl.sh)
--- path-to/tianon-bashbrew/library/buildkit	2024-06-25 14:53:40.000000000 -0700
+++ /dev/fd/63	2024-06-25 14:54:28.612188442 -0700
@@ -1,8 +1,12 @@
 Maintainers: Tianon Gravi <tianon@tianon.xyz> (@tianon)
 GitRepo: https://github.com/tianon/dockerfiles.git
+GitCommit: da8faac5ad0601a8948dee69e72ec669a9da9432
+Directory: buildkit
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, riscv64, s390x
 Builder: buildkit
 
 Tags: 0.14.1, 0.14, 0, latest
-GitCommit: 59e107d98a63148d38fe48bbbf4b42d3f1534099
-Directory: buildkit
+File: Dockerfile
+
+Tags: 0.13.2, 0.13
+File: Dockerfile.0.13
```

**Comment by tianon** [comment]
Overly pedantic Tianon results in:

```diff
$ diff -u path-to/tianon-bashbrew/library/buildkit <(./gsl.sh)
--- path-to/tianon-bashbrew/library/buildkit	2024-06-25 14:53:40.000000000 -0700
+++ /dev/fd/63	2024-06-25 14:57:52.738072071 -0700
@@ -1,8 +1,11 @@
 Maintainers: Tianon Gravi <tianon@tianon.xyz> (@tianon)
 GitRepo: https://github.com/tianon/dockerfiles.git
+GitCommit: 862ae508afd4aca17986a51f532dce097d23e339
+Directory: buildkit
 Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, mips64le, ppc64le, riscv64, s390x
 Builder: buildkit
 
 Tags: 0.14.1, 0.14, 0, latest
-GitCommit: 59e107d98a63148d38fe48bbbf4b42d3f1534099
-Directory: buildkit
+
+Tags: 0.13.2, 0.13
+File: Dockerfile.0.13
```

**Review by whalelines — COMMENTED** [review]
So you are simply building more BuildKit variants?

**Comment by thaJeztah** [comment]
> So you are simply building more BuildKit variants?

 they are "obviously Tianon" versions! 🥹

- https://github.com/tianon/dockerfiles/pull/722
- https://github.com/tianon/dockerfiles/pull/721

**Comment by tianon** [comment]
Yep, just more versions (especially so we can get a rebuild of our 0.13 with that fix we need for Kong, but also so it's easier for me to test things like RCs in the future)

**Pull request merged**
